inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - 'spec/dummy/db/schema.rb'
    - 'spec/dummy/vendor/**/*'
    - 'spec/fixtures/**/*'
    - 'spec/dummy/tmp/**/*'
    - 'spec/dummy/bin/**/*'
    - 'spec/dummy/db/**/*'
    - 'bin/**/*'
    - 'db/**/*'
  TargetRubyVersion: 2.4

Style/Encoding:
  EnforcedStyle: never
  Enabled: true

Style/FrozenStringLiteralComment:
  EnforcedStyle: always

Layout/EndOfLine:
  EnforcedStyle: lf

Layout/IndentHeredoc:
  EnforcedStyle: powerpack

Lint/AmbiguousBlockAssociation:
  Exclude:
    - 'spec/**/*.rb'

Lint/UselessAccessModifier:
  MethodCreatingMethods:
    - 'def_matcher'
    - 'def_node_matcher'

Metrics/BlockLength:
  Exclude:
    - 'Rakefile'
    - '**/*.rake'
    - 'spec/**/*.rb'

Metrics/ModuleLength:
  Exclude:
    - 'spec/**/*.rb'